### ISSUE TITLE
hard to find tools

### ISSUE THREAD

**Issue by bluecollarboysgaming** [42MonthsAfter/42MonthsAfter-Public#498]
car parts are to abundant

**Comment by BnYrB** [comment]
Clarifying question, is that because cars are being found / claimed complete? So there is no real need to go out an find parts? 

There are a couple different ways that we could approach this,

1. Make cars less complete and require more grinding to complete and up the amount of tools a slight bit

or

2. drop the number of car parts and not worry about it. 

I kind of like #1 personally.

**Comment by bluecollarboysgaming** [comment]
First one is fine

**Comment by BnYrB** [comment]
Sounds good! We will close this out then and I will update the car parts to randomize with less accessories.
