### ISSUE TITLE
Climbing into back of conquerer leads to crash

### ISSUE THREAD

**Issue by PartyBear666** [42MonthsAfter/42MonthsAfter-Public#548]
I'm at the holler and climbed into the back of the truck bed to attempt to get the hardig out and the game crashed and can't log back in? Haha

**Comment by BnYrB** [comment]
when you say climb in the back do you mean up into the bed?

**Comment by PartyBear666** [comment]
Yessir- I knew of the bug during the test server where climbing on the cars sent you under the map but this just kept crashing. It quickly sorted itself with the server messages "unlinked player/ linked player" but only after a few crashes while logging back in. Just a heads up

**Comment by BnYrB** [comment]
The crashing and not being to log back in is new. If you jump on the hood of a vanilla car you sometimes for a moment fall and see water then end up right were you were supposed to be.  This is just a DayZ bug, but the crashing is new. Let me know if it happens again and I'll try to reproduce it.

**Comment by BnYrB** [comment]
So I think I've figured out what this is.... There has been a bug since 1.18 with cars, even vanilla, where you fall into the map for a second when climbing on top of them. I think this is the same for climbing INTO our larger vehicles OR ones where there are impact zones "above" where you are trying to climb onto. The game can't figure out where to place you and it can cause a relog loop. 

If this happens again, let me know and I will try to TP you right next to your car to get you out of the loop

I don't think there is anything we can do but report this to DayZ and the maker of our car mods to get on their radar. Cars are rumored to be part of the update for 1.19 so maybe this will get resolved then?

**Comment by BnYrB** [comment]
Until then, I wouldn't climb into the back of the truck. I tested about 50 times on the hood and while I got the falling thing a few times I never got the boot loop. Same if I climbed from the front then onto the trunk area (even though it was open aka not covered)

I will put this in the known bugs channel. Appreciate you reporting it!
