### ISSUE TITLE
Death

### ISSUE THREAD

**Issue by MaxCaliber** [42MonthsAfter/42MonthsAfter-Public#571]
So, lost all my gear due to a horde of zombies respawning before a reset. After I had already just cleared the area. Then, I just randomly died while driving, my new UAZ is probably wrecked due to NOTHING. I could not see anything I ran into. Just dead. Again!

**Comment by BnYrB** [comment]
According to the logs you died from bleeding out right before the noon restart.  Then there are three "killed by environments' in a row at 1:20, 1:30 and again at 3: 20 pm EST. All of these last three are in different locations.

Did you bleed out while driving and that is what caused the wreck? Did the wreck happen at the wood working industrial place? 

Need more info to help sort out.

Zombies have a radius and time period that the use for triggering respawns, it's possible to have cleared an area, the respawn time which by default it 30 minutes but be in the town but outside of the "don't respond radius. In this event, you could just sit in cycle zombies every 30 minutes.

**Comment by MaxCaliber** [comment]
I died the first time in wood working from bleeding out after getting jumped. I wasn't even there for 15 minutes and they respawned on me. The last one was when my truck hit apparently a bush and blew up my UAZ. It wasn't damaged before this. Just blew up and I died. Wasn't even there when I got back, but smoke was coming under the map from a small island close by

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BnYrB** [comment]
Let me look into it after work.

**Comment by BnYrB** [comment]
So I tested the respawning zombies and, this is just a guess that will need more exploration, but it looks like there are two zones instead of 1 for that area, so you could run from one end to the other and IF you get far enough from 1 for the zombies to despawn, they will respawn, regardless of how long it takes. 

So if this is right, that means you could run back and forth and just respawn over and over.  I will need to dive into the map areas to see if thats accurate.

For the truck, this is with two different vehicles? You were driving a truck up to your spot when it blew up A DIFFERENT car? The UAZ? So it was parked?

**Comment by MaxCaliber** [comment]
I primarily use the UAZ to get around, had the M3S for hauling base mats. I was driving the UAZ up to my spot and apparently hit a bush and blew up instantly. The M3S was fine and sitting where I left it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
